#ifndef BITCOIN_CRYPTO_YESPOWER_INSECURE_MEMZERO_H
#define BITCOIN_CRYPTO_YESPOWER_INSECURE_MEMZERO_H

#define insecure_memzero(buf, len) /* empty */

#endif // BITCOIN_CRYPTO_YESPOWER_INSECURE_MEMZERO_H
