name: Check Merge Fast-Forward Only

permissions:
  contents: read

on:
  push:
  pull_request_target:

jobs:
  check_merge:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "noreply@example.com"

      - name: Check merge --ff-only
        env:
          PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            echo "Already on main, no need to check --ff-only"
          else
            git fetch --no-tags origin main:main
            if [[ "$GITHUB_EVENT_NAME" == "pull_request"* ]]; then
              git check-ref-format "refs/heads/$PR_BASE_REF"
              [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]
              git fetch --no-tags origin "refs/heads/$PR_BASE_REF:base_branch"
              git checkout base_branch
              git pull --rebase=false origin "pull/$PR_NUMBER/head"
              git checkout main
              git merge --ff-only base_branch
            else
              git checkout main
              git merge --ff-only "$GITHUB_SHA"
            fi
          fi

      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        if: failure()
        with:
          labels: |
            needs rebase

      - name: comment
        uses: mshick/add-pr-comment@v2
        if: failure()
        with:
          message: |
            This pull request has conflicts, please rebase.
